variables:
  PROJECT: Phoebus
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - Hygiene
  - Test

.ubuntu:
  image: ubuntu:20.04
  before_script:
    # Install packages
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update -qq
    - apt-get install -qq --no-install-recommends tzdata
    - apt-get install -qq git
    - apt-get install -qq make cmake g++
    - apt-get install -qq libopenmpi-dev libhdf5-openmpi-dev
    - apt-get install -qq python3 python3-numpy python3-h5py python3-matplotlib
    - apt-get install -qq lua5.3 liblua5.3-dev
    - apt-get upgrade -qq
    - apt-get -f install -qq

  script:
    # build the code
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DPHOEBUS_ENABLE_UNIT_TESTS=ON -DCMAKE_CXX_COMPILER=mpic++ ..
    - make -j
    - make test

# Darwin machine settings
.darwin:
  tags:
    - darwin-slurm-shared
  variables:
    http_proxy: "http://proxyout.lanl.gov:8080"
    https_proxy: "http://proxyout.lanl.gov:8080"
    SITE_ID: darwin
    DEPLOY: "FALSE"
    SP_x86_64: "--nodes=1 --partition=general --qos=debug --constraint='cpu_family:broadwell|cpu_family:haswell'"
    SP_power9: "--nodes=1 --partition=power9 --qos=debug"
    SP_arm: "--nodes=1 --partition=arm --qos=debug"
    SP_x86_volta: "--nodes=1 --partition=volta-x86 --qos=debug"

.darwin_merge:
  extends: .darwin
  #variables:
  #  CTEST_MODE: Experimental
  before_script:
    # Install packages
    - module load git
    - module load cmake
    - module load gcc/9.3.0
    - module load openmpi/4.0.3-gcc_9.3.0
    - module load cuda/9.1
    - module load python/3.5.1
    - module load lua/5.3.4

  script:
    # build the code
    - mkdir build && cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug -DPHOEBUS_ENABLE_UNIT_TESTS=ON -DPHOEBUS_ENABLE_HDF5=OFF -DCMAKE_CXX_COMPILER=mpic++ ..
    - make -j
    - make test

darwin_volta:
  stage: Test
  extends: .darwin_merge
  variables:
    CMAKE_BUILD_TYPE: Release
    CTEST_NPROC: 10
    MAXLOAD: 40
    SCHEDULER_PARAMETERS: ${SP_x86_volta}

ubuntu_x86:
  stage: Test
  extends: .ubuntu

clang-format:
  stage: Hygiene
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
  script:
    #  Call a script that checks for style
    - mkdir build && cd build
